### PR TITLE
regression: status icon in Code Lens is wrong

### LINKED ISSUE #646: Class level displays incorrect status icon
### How to repro:
1. Open a java project and open a test java file containing multiple test methods
2. Trigger test from one method 

### Result:
image

### Expect:
image

### PR DESCRIPTION
**Pull request by jdneo**
Fix #646

### CODE REVIEW

File: src/codeLensProvider.ts [hunk 1]
```diff
@@ -100,7 +101,9 @@ class TestCodeLensProvider implements CodeLensProvider {
                     testMethodMap.set(child.fullName, child);
                 }
                 for (const key of resultsInFsPath.keys()) {
-                    testResults.push(Object.assign({fullName: key, displayName: key}, testMethodMap.get(key), { details: resultsInFsPath.get(key) as ITestResultDetails }));
+                    if (key.startsWith(`${test.fullName}#`)) {
```
Comment (Eskibear) [inline src/codeLensProvider.ts]: better to add comment for the trick
