### PR TITLE
Regression: Cannot correctly parse the JUnit 5 ParameterizedTest result

### LINKED ISSUE #858: Show wrong result after run junit5 ParameterizedTest case
### Environment:

OS: Windows
JDK: 8/12
Java Extensions:

- Language Support for Java(TM) by Red Hat： 0.52.0
- Debugger for Java: 0.23.0
- Java Test Runner: 0.21.0

### Steps to reproduce:

1. Open the JUnit5 project in VSCode: https://github.com/ZhengJun003/junit5-samples/tree/testrunner
2. Run `CalculatorTests` in the test explorer

### Result:
image

### PR DESCRIPTION
**Pull request by jdneo**
fix #858

### CODE REVIEW

File: src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts [hunk 1]
```diff
@@ -25,7 +25,12 @@ export class JUnitRunnerResultAnalyzer extends BaseRunnerResultAnalyzer {
     protected processData(data: string): void {
         if (data.startsWith(MessageId.TestStart)) {
             const testFullName: string = getTestFullName(data);
-            if (testFullName) {
+            if (!testFullName) {
+                return;
+            }
+
+            const result: ITestResultDetails | undefined = this.testResults.get(testFullName);
+            if (!result) {
```
Comment (Eskibear) [inline src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts]: `!this.testResults.get(testFullName)`
