### PR TITLE
bugfix: Cannot run all tests for TestNG

### LINKED ISSUE #921: Can't run all test cases of TestNG project when there are test file in the editor
### Environment:

- OS: Win10
- JDK: 8
- Java Test Runner Extension: 0.22.0

### Repro steps:

1. OpenTestNG project [TestNG-Spring-Example](http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip) and comment `com.mkyong.testng.examples.group.TestGroup.runFinal()` method.
2. Run or Debug test project
    - Running the test in Workspace Root by click `Run All Tests` button 
    - Running the test in Workspace Folder level

### Result:
It's only run the test case `com.mkyong.testng.examples.group.TestGroup`
image

### PR DESCRIPTION
**Pull request by jdneo**
fix #921

### CODE REVIEW

File: src/runners/testngRunner/TestNGRunner.ts [hunk 1]
```diff
@@ -1,20 +1,26 @@
...
 import { BaseRunnerResultAnalyzer } from '../baseRunner/BaseRunnerResultAnalyzer';
 import { TestNGRunnerResultAnalyzer } from './TestNGRunnerResultAnalyzer';
 
 export class TestNGRunner extends BaseRunner {
 
     public getRunnerCommandParams(): string[] {
-        return ['testng', ...this.tests.map((t: ITestItem) => t.fullName)];
+        return ['testng', ...this.testIds.map((id: string) => {
+            // parse to fullName
+            const index: number = id.indexOf('@') + 1;
```
Comment (Eskibear) [inline src/runners/testngRunner/TestNGRunner.ts]: `id.indexOf('@')` returns -1 or N, thus `index > -1` is always true.
