### PR TITLE
fix: print the unexpected exceptions to the output channel

### LINKED ISSUE #537: TestNG test cases will be skipped
According to https://github.com/Microsoft/vscode-java-test/issues/504#issuecomment-445131893 by @bsaby 

The TestNG test cases will be skipped if triggering from workspace root level and workspace folder level.

## Root cause
In `com.mkyong.testng.examples.group.TestGroup`, some of the codes are commented. Release them will make the runner running successfully.

## How to fix
I will investigating if there is a way to let the runner run other tests no matter the usage of `dependsOnGroups`

### PR DESCRIPTION
**Pull request by jdneo**
Fix #537 

### Previous Behavior
The extension won't show anything when exception happens

### Now
Give the user a hint
demo

### CODE REVIEW

File: src/runners/runnerExecutor.ts [hunk 1]
```diff
@@ -75,13 +77,17 @@ class RunnerExecutor {
...
             }
-        } catch (error) {
-            window.showErrorMessage(`${error}`);
-            testStatusBarProvider.showFailure();
-        } finally {
             testStatusBarProvider.showTestResult(finalResults);
             testCodeLensProvider.refresh();
             testReportProvider.update(finalResults);
+        } catch (error) {
+            window.showErrorMessage(`${error}`, OPEN_OUTPUT_CHANNEL).then((choice: string | undefined) => {
```
Comment (Eskibear) [inline src/runners/runnerExecutor.ts]: `${error}` = error ?

Comment (jdneo) [reply src/runners/runnerExecutor.ts]: Good catch
