### PR TITLE
fix classpath issue for multiple projects in a workspace folder

### LINKED ISSUE #176: 多模块项目classpath问题
在工作空间有多个项目时(A,B)，运行A项目的test case，classpath中有B项目的目录,A并没有依赖于B,使用maven运行test case是正常的

### PR DESCRIPTION
**Pull request by ansyral**
Signed-off-by: xuzho <xuzho@microsoft.com>

to fix #176

### CODE REVIEW

File: extension/src/classPathManager.ts [hunk 1]
```diff
@@ -2,19 +2,24 @@
...
 
 import { workspace, CancellationToken, Uri } from 'vscode';
+import { ProjectManager } from './projectManager';
 import * as Commands from './Constants/commands';
 import * as Logger from './Utils/Logger/logger';
 
 export class ClassPathManager {
-    private classPathCache = new Map<string, string[]>();
+    // mapping from project folder uri to classpaths.
+    private classPathCache = new Map<Uri, string[]>();
```
Comment (yaohaizh) [inline extension/src/classPathManager.ts]: Naming convention:  underscore with private members.

File: extension/src/classPathManager.ts [hunk 2]
```diff
@@ -2,19 +2,24 @@
...
         if (!workspace.workspaceFolders) {
             return;
         }
-        return Promise.all(workspace.workspaceFolders.map((wkspace) => {
-            return calculateClassPath(wkspace.uri).then((classpath: string[]) => {
-                this.storeClassPath(wkspace.uri, classpath);
+        await this._projectManager.refresh();
+        return Promise.all(this._projectManager.getAll().map((info) => {
+            return calculateClassPath(info.path).then((classpath: string[]) => {
+                this.storeClassPath(info.path, classpath);
```
Comment (yaohaizh) [inline extension/src/classPathManager.ts]: simplify to oneline?
