### PR TITLE
fix: Can select peer project if current project does not contain test framework

### LINKED ISSUE #1208: Support "Generate Test..." into a standalone test project for multi modules
When trying "Generate Test..." feature in `org.eclipse.jdt.ls.core` project, it failed because my project didn't contain any unit test framework. But actually all my test cases are placed at a separate project `org.eclipse.jdt.ls.tests`.

image

Ideas:

If current project doesn't contain any unit test framework, then search the whole workspace to see if there is any other peer project with test cases. And ask user to confirm whether to generate test cases in another project.

### PR DESCRIPTION
**Pull request by jdneo**
fix #1208

https://user-images.githubusercontent.com/6193897/119313404-15b97200-bca6-11eb-88c2-33702b4bc217.mp4

### CODE REVIEW

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 1]
```diff
@@ -559,6 +563,38 @@ private static WorkspaceEdit generateTestsFromTest(ICompilationUnit unit, Compil
...
+            if (TestKindProvider.getTestKindsFromCache(project).size() > 0) {
+                javaTestProjects.add(new Option(project.getHandleIdentifier(), project.getElementName(),
+                    project.getProject().getLocation().toOSString()));
+            }
+        }
+
+        if (javaTestProjects.size() == 0) {
+            JavaLanguageServerPlugin.getInstance().getClientConnection().showNotificationMessage(MessageType.Error,
+                    "The projects in the workspace do not have a test framework," +
+                    " please make sure they are configured correctly.");
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:587]: No test library found in your workspace, please add a test library to your project classpath first.

**Review by testforstephen — APPROVED** [review]
