### PR TITLE
Fix the "Cannot read property 'indexOf' of undefined" bug when running JUnit 5 tests

### LINKED ISSUE #455: Failed to parse output data: Cannot read property 'indexOf' of undefined
I can see this log in the output channel when running JUnit 5 test cases.

The root cause is the regex here: https://github.com/Microsoft/vscode-java-test/blob/master/extension/src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts#L47

### PR DESCRIPTION
**Pull request by jdneo**
Fix #455

### CODE REVIEW

File: extension/src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export class JUnit5RunnerResultAnalyzer extends BaseRunnerResultAnalyzer {
         if (!id) {
             return id;
         }
-        const regex: RegExp = /\[class:(.*?)\](?:\/\[method:(.*)\])?/gm;
+        const regex: RegExp = /\[class:(.*?)\]\/\[method:(.*)\]/gm;
         const match: RegExpExecArray | null = regex.exec(id);
         if (match) {
             if (match.length === 2) {
```
Comment (Eskibear) [inline extension/src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts]: `match.length === 2` not possible for current regexp
