### PR TITLE
fix: Can generate tests from interface, enum and record

### LINKED ISSUE #1206: Support "Generate Test..." in interface methods
image

Since the interfaces could add default implementation for method, we should allow to add tests for interface methods as well.

### PR DESCRIPTION
**Pull request by jdneo**
fix #1206

### CODE REVIEW

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 1]
```diff
@@ -139,20 +139,20 @@ public static WorkspaceEdit generateTests(List<Object> arguments, IProgressMonit
...
 
-        final ITypeBinding binding = ((TypeDeclaration) coveringNode).resolveBinding();
+        final ITypeBinding binding = ((AbstractTypeDeclaration) coveringNode).resolveBinding();
         if (binding == null) {
             JUnitPlugin.logError("Failed to resolve type binding from " + unit.getElementName());
             return null;
         }
 
-        if (!binding.isClass()) {
+        if (!(binding.isClass() || binding.isInterface() || binding.isRecord())) {
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:153]: does this support enum type?

Comment (jdneo) [reply java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:153]: Yes it does in IntelliJ, will cover that case

**Review by testforstephen — DISMISSED** [review]

**Review by testforstephen — APPROVED** [review]
