### PR TITLE
fix: Regression bug that cannot show execution time of the tests

### LINKED ISSUE #871: All tests always produce "N/A" execution time
Hello,
I've noticed that no matter what I do, under any circumstance (test fails, test passes, separate projects, etc.) the execution time listed for all tests is `N/A`. I also asked a friend who uses Java testing in VS Code and they also have the issue.

### PR DESCRIPTION
**Pull request by jdneo**
fix #871

### CODE REVIEW

File: src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts [hunk 1]
```diff
@@ -29,13 +29,20 @@ export class JUnitRunnerResultAnalyzer extends BaseRunnerResultAnalyzer {
...
                 if (data.indexOf(MessageId.IGNORE_TEST_PREFIX) > -1) {
                     detail.status = TestStatus.Skip;
+                } else {
+                    detail.duration = - Date.now();
                 }
                 this.testResults.set(testFullName, detail);
+            } else if (detail.duration !== undefined) {
+                // Some test cases may executed multiple times (@RepeatedTest), we need to calculate the time for each execution,
+                // so here plus is used.
+                detail.duration += - Date.now();
```
Comment (testforstephen) [inline src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts]: hard to understand it.  `duration -= startTime;`

Comment (jdneo) [reply src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts]: Updated
