### PR TITLE
fix: use listen(0) for OS auto-port-allocation instead of getPort

### LINKED ISSUE #1854: When running Java unit tests via Test Runner for Java in WSL2, the UI stays stuck at:   Resolving launch configuration...
## Bug Description
  When running Java unit tests via Test Runner for Java, the UI stays stuck at:
  Resolving launch configuration...

  ## Root Cause
  VS Code Test Runner for Java 0.44.0 creates a local socket server before launching tests. It uses `get-port` to pre-select a port, then closes the probe socket and rebinds to the same port on
  `127.0.0.1`. In WSL/Windows port environments, this "pre-select then rebind" pattern causes massive `EADDRINUSE` failures.

  Evidence from VS Code extension log:
  Error: listen EADDRINUSE: address already in use 127.0.0.1:46129
  Error: listen EADDRINUSE: address already in use 127.0.0.1:46423
  Error: listen EADDRINUSE: address already in use 127.0.0.1:46333
  Error: listen EADDRINUSE: address already in use 127.0.0.1:46049
  Error: listen EADDRINUSE: address already in use 127.0.0.1:45865

  ## Reproduction
  The problematic pattern in the extension:
  ```js
  const port = await getPort();  // Step 1: reserve a port
  server.listen(port, "127.0.0.1", callback);  // Step 2: rebind to same port
  In the affected environment, ~96 out of 100 such attempts fail.

  Suggested Fix

  Replace the two-step port selection with direct port allocation:
  server.listen(0, "127.0.0.1", callback);  // OS auto-assigns a free port
  This approach achieves 0 failures in the same environment.

  Environment

  - OS: Windows + WSL
  - VS Code Test Runner for Java: 0.44.0
  - Multiple JDKs installed (Java 8, 21, 25)

### PR DESCRIPTION
**Pull request by inkpark**
fix: use listen(0) for OS auto-port-allocation instead of getPort pre-selection

In WSL/Windows port environments, the two-step pattern of reserving a
      port with getPort() then rebinding to it caused massive EADDRINUSE
      failures (~96 out of 100 attempts). Replacing with
server.listen(0)
      lets the OS auto-assign a free port in a single step, achieving 0
      failures in the same environment.
Fixes #1854

### CODE REVIEW

**Comment by inkpark** [comment]
> @inkpark please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.@inkpark 请阅读以下的Contributor License Agreement(贡献者许可协议)。如果你同意CLA，请回复以下信息。
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (默认 - 未指定公司) 我对我的提交内容拥有 sole 知识产权，并且我不是在为雇主工作的过程中进行提交。
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * （当公司 given 时）我在为雇主工作期间进行提交（或者根据合同或适用法律，我的雇主对我的提交内容拥有知识产权）。我已获得雇主的许可，可以代表我的雇主进行 Submissions(提交内容) 并签订本协议。通过在下方签名，定义的术语“ You”包括我和我的雇主。
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> 贡献者许可协议 Contributor(贡献者)



> @inkpark please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.@inkpark 请阅读以下的Contributor License Agreement(贡献者许可协议)。如果你同意CLA，请回复以下信息。
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (默认 - 未指定公司) 我对我的提交内容拥有 sole 知识产权，并且我不是在为雇主工作的过程中进行提交。
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * （当公司 given 时）我在为雇主工作期间进行提交（或者根据合同或适用法律，我的雇主对我的提交内容拥有知识产权）。我已获得雇主的许可，可以代表我的雇主进行 Submissions(提交内容) 并签订本协议。通过在下方签名，定义的术语“ You”包括我和我的雇主。
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> 贡献者许可协议 Contributor(贡献者)

@microsoft-github-policy-service agree

File: src/runners/baseRunner/BaseRunner.ts [hunk 1]
```diff
@@ -1,7 +1,6 @@
 // Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the MIT license.
 
-import getPort from 'get-port';
```
Comment (chagong) [inline src/runners/baseRunner/BaseRunner.ts:4]: Can you remove get-port from dependencies then?

Comment (inkpark) [reply src/runners/baseRunner/BaseRunner.ts:4]: Removed the unused `get-port` dependency from `package.json` and `package-lock.json`, and cleaned up the corresponding entry in `ThirdPartyNotices.txt`. There are no remaining `get-port` usages in the repo.

**Review by chagong — APPROVED** [review]

**Comment by chagong** [comment]
@inkpark Thanks for your contribution!
