### PR TITLE
Fix the bug that status icon is not right in the inner test class

### LINKED ISSUE #586: A question status icon will be added as the third Code Lens automatically for inner class
### Build
416
### Steps:

1. Open a java file.
2. Trigger tests from the outer class codelens

OR
1. Open a java file and  and make sure you have the class with a status icon
2. Add a new inner class
3. Save file

### Result:
A question status icon will be added automatically for inner class
Screenshot1:
image

Screenshot2:
image

### PR DESCRIPTION
**Pull request by jdneo**
Fix #586

### CODE REVIEW

File: src/codeLensProvider.ts [hunk 1]
```diff
@@ -76,12 +76,28 @@ class TestCodeLensProvider implements CodeLensProvider {
...
+                return testResultManager.getResultDetails(Uri.parse(test.uri).fsPath, test.fullName) !== undefined;
+            case TestLevel.Class:
+            case TestLevel.NestedClass:
+                const resultsInFsPath: Map<string, ITestResultDetails> | undefined = testResultManager.getResults(Uri.parse(test.uri).fsPath);
+                if (!resultsInFsPath) {
+                    return false;
+                }
+                const keyCollection: string[] = Array.from(resultsInFsPath.keys());
+                for (const child of test.children) {
+                    if (child.level !== TestLevel.Method) {
```
Comment (Eskibear) [inline src/codeLensProvider.ts]: I assume the body of the `for` statement can be simplified as the following?
```ts
if (child.level === TestLevel.Method && keyCollection.indexOf(child.fullName) >= 0) {
    return true;
}
```
