### PR TITLE
fix: Generated test methods reduced the visibility of the inherited methods

### LINKED ISSUE #1182: Generated test methods reduced the visibility of the duplicated methods from inherited class
Below are samples.
```java
public class A {
    @BeforeAll
    public static void beforeClass() {
    }

    @BeforeEach
    public void setUp() {
    }
}
```

```java
public class B extends A {
    @BeforeAll
    static void beforeClass() { // Generated lifecycle method will report error "Cannot reduce the visibility of the inherited method from A".
    }

    @BeforeEach
    void setUp() { // Generated lifecycle method will report error "Cannot reduce the visibility of the inherited method from A".
    }
}
```

Should check if the inherited class contains the same methods. If they're visible to the subclass, the subclass should not reduce the visibility of these methods. Also add `@Override` annotation for them.

### PR DESCRIPTION
**Pull request by jdneo**
Fix #1182

### CODE REVIEW

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 1]
```diff
@@ -358,6 +354,42 @@ private static String getSuggestedMethodNameByAnnotation(String annotation) {
...
+            modifiers |= Modifier.PUBLIC;
+        }
+
+        // @BeforeClass and @AfterClass in JUnit 4 & 5 needs static modifier
+        if (needStaticModifier(kind, annotation)) {
+            modifiers |= Modifier.STATIC;
+        }
+
+        ITypeBinding superClass = typeBinding.getSuperclass();
+        while (superClass != null) {
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:374]: If the super class contains a duplicate method, it's better to add `@Override` tag to the generated method in subclass.

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 2]
```diff
@@ -358,6 +354,42 @@ private static String getSuggestedMethodNameByAnnotation(String annotation) {
...
+            final IMethodBinding[] superMethods = superClass.getDeclaredMethods();
+            for (final IMethodBinding superMethod : superMethods) {
+                if (Objects.equals(superMethod.getName(), methodName)) {
+                    final int superModifiers = superMethod.getModifiers();
+                    // Cannot reduce the visibility of the inherited method
+                    if (Modifier.isPublic(superModifiers)) {
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:380]: both `protected`, `public` methods in super class are visible to subclass, and could override it in subclass.

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 3]
```diff
@@ -264,19 +266,13 @@ private static TextEdit getTextEdit(TestKind kind, List<MethodMetaData> methodMe
...
-
-            // @BeforeClass and @AfterClass in JUnit 4 & 5 needs static modifier
-            if (needStaticModifier(kind, method.annotation)) {
-                decl.modifiers().addAll(ASTNodeFactory.newModifiers(ast, Modifier.STATIC));
-            }
 
             // set a unique method name according to the annotation type
-            decl.setName(ast.newSimpleName(getUniqueMethodName(typeBinding.getJavaElement(),
-                    method.methodName)));
+            final String methodName = getUniqueMethodName(typeBinding.getJavaElement(), method.methodName);
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:271]: When finding unique method names, should also filter out the method names in super class with different signature.

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 4]
```diff
@@ -359,6 +373,60 @@ private static String getSuggestedMethodNameByAnnotation(String annotation) {
...
+            methods.put(methodBinding.getName(), methodBinding);
+        }
+        ITypeBinding superClass = typeBinding.getSuperclass();
+        while (superClass != null) {
+            for (final IMethodBinding methodBinding : superClass.getDeclaredMethods()) {
+                if (methods.containsKey(methodBinding.getName())) {
+                    continue;
+                }
+
+                if (Modifier.isPrivate(methodBinding.getModifiers())) {
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:420]: https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html

Members with private or no modifier are not accessible to subclass. Maybe the condition could be

```java
if (Modifier.isProtected(...) || Modifier.isPublic(...)) {
  methods.put(methodBinding.getName(), methodBinding);
}
```

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 5]
```diff
@@ -359,6 +374,77 @@ private static String getSuggestedMethodNameByAnnotation(String annotation) {
...
+        return methods;
+    }
+
+    private static boolean isAccessible(IMethodBinding superMethod, ITypeBinding declaredType) {
+        final int modifiers = superMethod.getModifiers();
+        if (Modifier.isPrivate(modifiers)) {
+            return false;
+        }
+
+        if (!Modifier.isProtected(modifiers) && !Modifier.isProtected(modifiers)) {
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:438]: typos.

!Modifier.isPublic(...)

File: java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java [hunk 6]
```diff
@@ -359,6 +374,77 @@ private static String getSuggestedMethodNameByAnnotation(String annotation) {
...
+        if (binding == null) {
+            return modifiers;
+        }
+
+        final int superModifiers = binding.getModifiers();
+        if (Modifier.isProtected(superModifiers)) {
+            modifiers |= Modifier.PROTECTED;
+        } else if (Modifier.isPublic(superModifiers)) {
+            modifiers |= Modifier.PUBLIC;
+        }
```
Comment (testforstephen) [inline java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java:403]: if it's JUnit 4, always return public regardless of super implementation.

**Review by testforstephen — APPROVED** [review]
