### PR TITLE
fix: Make sure extension could be activated

### LINKED ISSUE #1381: Tests are not found anymore since 0.34.1
When using version 0.34.1 (I did so on Gitpod) none of my tests are recognized anymore.
No play button is shown and  also in the Testing View no tests are shown. Everything works fine with 0.34.0

### PR DESCRIPTION
**Pull request by jdneo**
fix #1381 

Signed-off-by: Sheng Chen <sheche@microsoft.com>

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -69,13 +59,30 @@ async function doActivate(_operationId: string, context: ExtensionContext): Prom
             }));
         }
 
+        if (extensionApi.onDidClasspathUpdate) {
```
Comment (CsCherrYY) [inline src/extension.ts:62]: Why do we change the sequence of event listeners here?

Comment (jdneo) [reply src/extension.ts:62]: Just would like to register the server mode change event more earlier

Comment (CsCherrYY) [reply src/extension.ts:62]: get it

**Review by CsCherrYY — APPROVED** [review]
